export const regexMatch = [
  "/administrative closing/gi",
  "/bond/gi",
  "/copy request/gi",
  "/courtroom contact/gi",
  "/epayment instructions/gi",
  "/epayment expectations/gi",
  "/government parties/gi",
  "/hearings/gi",
  "/independent evaluator list/gi",
  "/interpreters/gi",
  "/jobs/gi",
  "/legal aid/gi",
  "/legal advice/gi",
  "/letters of authority/gi",
  "/no known heirs/gi",
  "/notice of hearing/gi",
  "/transcript/gi",
  "/where do i file/gi",
  "/will copy/gi",
  "/will filing/gi",
  "/will advice/gi",
  "/will search/gi",
  "/adoption records/gi",
  "/probate/gi",
  "/estate/gi",
  "/guardianship/gi",
  "/conservatorship/gi",
  "/will/gi",
  "/trust/gi",
  "/power of attorney/gi",
  "/death certificate/gi",
  "/asset/gi",
  "/debt/gi",
  "/creditor/gi",
  "/beneficiary/gi",
  "/hearing/gi",
  "/court/gi",
  "/judge/gi",
  "/lawyer/gi",
  "/attorney/gi",
  "/legal aid/gi",
  "/self-help/gi",
  "/filing/gi",
  "/document/gi",
  "/payment/gi",
  "/fee/gi",
  "/cost/gi",
  "/record/gi",
  "/search/gi",
  "/access/gi",
  "/information/gi",
  "/help/gi",
  "/advice/gi",
  "/support/gi",
];
